# Generated by Django 4.0.1 on 2022-03-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_auto_20220220_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url_title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
