# Generated by Django 4.0.1 on 2022-03-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_slidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='slide_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
