# Generated by Django 3.2.12 on 2022-04-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_articlecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecomments'),
        ),
    ]
