# Generated by Django 3.2.12 on 2022-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_auto_20220407_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
